#include "Report.h"

Report::Report(string id, string genBy, string dt, string rType) {
    reportID    = id;
    generatedBy = genBy;
    date        = dt;
    reportType  = rType;
}

void Report::generateSummary(vector<Candidate> candidates, Result result) {
    cout << "=============================" << endl;
    cout << "        ELECTION REPORT       " << endl;
    cout << "=============================" << endl;
    cout << "Report ID    : " << reportID    << endl;
    cout << "Generated By : " << generatedBy << endl;
    cout << "Date         : " << date        << endl;
    cout << "Type         : " << reportType  << endl;
    cout << "-----------------------------" << endl;
    cout << "Votes Per Candidate:" << endl;
    for (int i = 0; i < candidates.size(); i++) {
        cout << candidates[i].getName() << "-->  "
             << candidates[i].getVoteCount() << " votes" << endl;
    }
    cout << "-----------------------------" << endl;
    cout << "Total Votes : " << result.getTotalVotesCast() << endl;
    cout << "Winner      : " << result.getWinner()         << endl;
    cout << "=============================" << endl;
}

void Report::exportReport() {
    cout << "[Report Exported!]" << endl;
    cout << "Report ID : " << reportID << endl;
}
